server:
  port: 8090
  servlet:
    session:
      timeout: 30m
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: ssdemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: shu123#
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
  thymeleaf:
    cache: false
    mode: HTML
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
        enabled: true
        cache: false
      static-path-pattern:  /static/**
    mvc:
      view:
        prefix: classpath:/templates/
        suffix: .html
      pathmatch:
        use-suffix-pattern: false
        use-registered-suffix-pattern: true
      contentnegotiation:
        favor-path-extension: false
    servlet:
      multipart:
        enabled: true
        max-file-size:
          5MB
        max-request-size:
          50MB
mybatis:
  type-aliases-package: cn.ss.ssdemo.entity
  mapper-locations: classpath:mappers/*.xml
logging:
  config: classpath:logback-spring.xml
